### ISSUE TITLE
Did this break with the latest Things 3 release - Version 3.17.4 (31704515)?

### ISSUE THREAD

**Issue by jeredactyl** [thingsapi/things.py#102]
### Discussed in https://github.com/thingsapi/things.py/discussions/101

<div type='discussions-op-text'>

<sup>Originally posted by **jeredactyl** April 12, 2023</sup>
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/things-cli", line 33, in <module>
    sys.exit(load_entry_point('things-cli==0.1.4', 'console_scripts', 'things-cli')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things_cli/cli.py", line 487, in main
    ThingsCLI().main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things_cli/cli.py", line 406, in main
    self.main(ThingsCLI.get_parser().parse_args())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things_cli/cli.py", line 422, in main
    self.parse_command(defaults, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things_cli/cli.py", line 479, in parse_command
    self.print_tasks(getattr(api, command)(**defaults))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things/api.py", line 556, in anytime
    return tasks(start="Anytime", **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things/api.py", line 190, in tasks
    database = pop_database(kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things/api.py", line 719, in pop_database
    database = Database(filepath=filepath, print_sql=print_sql)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/things/database.py", line 164, in __init__
    with open(self.filepath) as file:
NotADirectoryError: [Errno 20] Not a directory: '/Users/xxxxxxx/Library/Group Containers/JLMPQHK86H.com.culturedcode.ThingsMac/Things `Database.thingsdatabase/main.sqlite'
```
</div>

**Comment by subokita** [comment]
Yes, they:
- moved the DB location, you can open the `/Users/xxxxx/Library/Group Containers/JLMPQHK86H.com.culturedcode.ThingsMac/` to find a readme that shows the new location (it's in the same folder, but now a subdirectory. You can point it using the `THINGSDB` environment variable
- But, they also changed some of the DB schema, renaming at least one of the column names, thus breaking things.py

**Comment by AlexanderWillner** [comment]
Partly solved, thanks for the contributions! Next step(s) to be discussed in #110
